---
name: LibA2
version: 0.07
author:
  - Christopher J. Madsen <cjm@pobox.com>
abstract: Apple II emulator & file utilities
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Getopt::Long: 2.10
  IO::File: 0
  perl: 5.6.0
build_requires:
  FindBin: 0
  Module::Build: 0
dynamic_config: 1
provides:
  AppleII::Disk:
    file: lib/AppleII/Disk.pm
    version: 0.06
  AppleII::Disk::DOS33:
    file: lib/AppleII/Disk.pm
  AppleII::Disk::ProDOS:
    file: lib/AppleII/Disk.pm
  AppleII::ProDOS:
    file: lib/AppleII/ProDOS.pm
    version: 0.06
  AppleII::ProDOS::Bitmap:
    file: lib/AppleII/ProDOS.pm
  AppleII::ProDOS::DirEntry:
    file: lib/AppleII/ProDOS.pm
  AppleII::ProDOS::Directory:
    file: lib/AppleII/ProDOS.pm
  AppleII::ProDOS::File:
    file: lib/AppleII/ProDOS.pm
  AppleII::ProDOS::Index:
    file: lib/AppleII/ProDOS.pm
  AppleII::ProDOS::Members:
    file: lib/AppleII/ProDOS.pm
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
