---
name: LibA2
version: 0.04
author:
  - Christopher J. Madsen <cjm@pobox.com>
abstract: Apple II emulator & file utilities
license: perl
requires:
  Getopt::Long: 2.10
  IO::File: 0
  perl: 5.6.0
build_requires:
  FindBin: 0
  Module::Build: 0
dynamic_config: 1
provides:
  AppleII::Disk:
    file: lib/AppleII/Disk.pm
    version: 0.04
  AppleII::Disk::DOS33:
    file: lib/AppleII/Disk.pm
    version: 0.04
  AppleII::Disk::ProDOS:
    file: lib/AppleII/Disk.pm
    version: 0.04
  AppleII::ProDOS:
    file: lib/AppleII/ProDOS.pm
    version: 0.04
  AppleII::ProDOS::Bitmap:
    file: lib/AppleII/ProDOS.pm
    version: 0.04
  AppleII::ProDOS::DirEntry:
    file: lib/AppleII/ProDOS.pm
    version: 0.04
  AppleII::ProDOS::Directory:
    file: lib/AppleII/ProDOS.pm
    version: 0.04
  AppleII::ProDOS::File:
    file: lib/AppleII/ProDOS.pm
    version: 0.04
  AppleII::ProDOS::Index:
    file: lib/AppleII/ProDOS.pm
    version: 0.04
  AppleII::ProDOS::Members:
    file: lib/AppleII/ProDOS.pm
    version: 0.04
generated_by: Module::Build version 0.2604
